### ISSUE TITLE
Android PERMISSION_CODE is the same as location_permissions PERMISSION CODE

### ISSUE THREAD

**Issue by ened** [BaseflowIT/flutter-permission-handler#111]
## 🔙 Regression

This will cause conflicts with the latest geolocator plugin because it uses the location_permissions package and thus we can not retrieve location permission request results in here when both projects are used.

Will submit a new PR which uses a different request code:

 - https://github.com/BaseflowIT/flutter-permission-plugins/blob/develop/packages/location_permissions/android/src/main/java/com/baseflow/location_permissions/LocationPermissionsPlugin.java#L38
 - https://github.com/BaseflowIT/flutter-permission-handler/blob/develop/android/src/main/java/com/baseflow/permissionhandler/PermissionHandlerPlugin.java#L36

### Configuration

**Version:** 3.0.2

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android

**Comment by mvanbeusekom** [comment]
I will wait for this PR before rolling a new release.

Are we free to pick any request code we want? I choose 25 because I read it somewhere in the Google Documentation and to be honest I didn't really investigate the use of the code, figured it was some kind of Android constant that had to be used.

**Comment by ened** [comment]
Fixed in #113.
