### ISSUE TITLE
permission status changed callback

### ISSUE THREAD

**Issue by aytunch** [BaseflowIT/flutter-permission-handler#117]
I am not sure if the following accomplishes this for location:

`ServiceStatus serviceStatus = await PermissionHandler().checkServiceStatus(PermissionGroup.location);`

I could not find in the documentation as to what this exactly does. Does it fire when the location permission changes state? If yes, I will use it in my app.

Also, is it possible to have similar callbacks for every permission type(contacts, mic, photo, etc..), so that we don't need to check every time the app goes to background/foreground for `checkPermission`?

**Comment by mvanbeusekom** [comment]
@aytunch, this call is only available for the location services and directly returns a value indicating if location services are available (or running) on the device.

So this is not directly permission related since it only reports if the `location services` are turned on/off on the device and doesn't say anything about if permissions are granted or denied.

Also this is not a callback or stream since these API's are not available in the native SDKs, it is simply a method call that (asynchronously) returns information about the service. Possible values are:

```
/// Defines the state of a service related to the permission group
enum ServiceStatus {
  /// The unknown service status indicates the state of the service could not be determined.
  unknown,

  /// There is no service for the supplied permission group.
  notApplicable,

  /// The service for the supplied permission group is disabled.
  disabled,

  /// The service for the supplied permission group is enabled.
  enabled
}
```
