### ISSUE TITLE
Add WRITE_SMS Permission and Setting as Default SMS Application

### ISSUE THREAD

**Issue by ThinkDigitalRepair** [BaseflowIT/flutter-permission-handler#25]
## 🚀 Feature Requests

WRITE_SMS Permission

### Contextualize the feature

Sorry, don't understand this
### Describe the feature
This would allow the app to write SMS to the phone. It should also allow the setting of the app as the default SMS application and allow changing back the default SMS application as well since this permission would be pointless without the option to set as default.

### Platforms affected (mark all that apply)
- [ ] :iphone: iOS
- [✓] :robot: Android

**Comment by mvanbeusekom** [comment]
@ThinkDigitalRepair, I have been researching `WRITE_SMS` permissions and found that it is not part of the `Manifest.permission` class which contains all permission constants. Doing a bit of searching I found out that it has been removed by Google starting from API level 23 (see also [here](https://android.stackexchange.com/questions/157905/permission-system-changes-with-android-6-0-what-are-the-implications-for-us-use)).

Apparently Google doesn't want us to use it anymore. Do you have any specific reasons, or maybe instructions on how this could still be accomplished?

**Comment by ThinkDigitalRepair** [comment]
I found it in the switching to KitKat API updates article or whatever. I
added it to my manifest and added a way to do it from the Java code,
although I couldn't figure out how to do it dynamically.

**Comment by ThinkDigitalRepair** [comment]
For reasons, you can't fully manage SMS without being set as the default
application and you won't appear as an sms program at all without them.
https://android-developers.googleblog.com/2013/10/getting-your-sms-apps-ready-for-kitkat.html

**Comment by mvanbeusekom** [comment]
@ThinkDigitalRepair thank you for your feedback, learned something new today ;). 

Unfortunately we will not be implementing the feature to set your App as the default SMS application in this plugin. To do so would mean that the plugin needs to handle all in- and outbound SMS intents which is very specific behaviour which we feel moves away from the intent of this plugin (namely, handling permissions of all sorts).

Since the `WRITE_SMS` is also no longer available on Android (since API 23) and it is quite hard to implement it based on older SDK's we will also not implement that in this plugin, although pull-request are always welcome.
