### ISSUE TITLE
Unresolved reference: ActivityCompat

### ISSUE THREAD

**Issue by shinayser** [BaseflowIT/flutter-permission-handler#39]
I jsut added it to my project and getting the following error hen trying to compile:
![image](https://user-images.githubusercontent.com/1146982/48015215-ae4f6d00-e10f-11e8-8840-0474fd1c2a69.png)

 
Unresolved reference: ActivityCompat 
Unresolved reference: content 
Unresolved reference: ContextCompat 
Unresolved reference: ActivityCompat 
Unresolved reference: ActivityCompat 87 actionable tasks: 5 executed, 82 up-to-date 

Any clue about what could possibly going wrong? 
Obs.: my project was completely migrated to androidx packages.

**Comment by mvanbeusekom** [comment]
@shinayser from what I am seeing is that AndroidX packages are not yet supported on Flutter (see also the issue [Flutter/Flutter#23586](https://github.com/flutter/flutter/issues/23586)). 

Until this is supported correctly by Flutter we won't be able to fix this issue (at the moment we have to depend on the "old" Android Support packages). I am am wrong please let me know since I am no Android expert.
